# Generated by Django 5.2.1 on 2025-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_sale_sold_by_drug_updated_by_sale_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="sale_price",
        ),
        migrations.AddField(
            model_name="sale",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
