# Generated by Django 5.2.1 on 2025-05-17 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_sale_created_by_remove_sale_sale_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="sale_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
