# Generated by Django 5.2.1 on 2025-05-18 09:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_sale_created_by_sale_sale_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Debtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_sold", models.PositiveIntegerField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("customer_name", models.CharField(blank=True, max_length=100)),
                ("date_sold", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.drug"
                    ),
                ),
            ],
        ),
    ]
