# Generated by Django 5.2.1 on 2025-05-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_debtor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="acknowledgements/")),
            ],
        ),
        migrations.CreateModel(
            name="Investor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="investors/")),
            ],
        ),
    ]
